name: CI
on: [pull_request]
jobs:
  lint:
    name: PSScriptAnalyzer checks
    steps:
      - uses: actions/checkout@v1
      - name: lint
        uses: devblackops/github-action-psscriptanalyzer@v2.0.0
        with:
          rootPath: SteamPS
          settingsPath: PSScriptAnalyzerSettings.psd1
          sendComment: true
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          failOnErrors: true
          failOnWarnings: true
          failOnInfos: true
