install:
- ps: . .\install.ps1
skip_commits:
  message: /updated readme.*|update readme.*s|update docs.*|update version.*|update appveyor.*/
  files:
  - README.md
environment:
  NuGetApiKey:
    secure: 8YlpDDR3+ijAeAxFBSPqFgYIk+kehh0ypKPVa5yrmWCFdFoswFw1pZ/kZmOyMdjS
  GitHubKey:
    secure: N7+lKlNrQkJHEtEtl1CcwG9Q3GRLbH9kGD41NWfb0GbLsH9rHjMoIiCVkDF8jolr
version: 2.0.0.{build}
test_script:
- git config --global credential.helper store
- ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:GitHubKey):x-oauth-basic@github.com`n"
- git config --global user.email "first.last@domain.com"
- git config --global user.name "First Last"
- git config --global core.autocrlf true
- git config --global core.safecrlf false
- ps: Write-Host -Object "--- Calling build.ps1 ---"
- ps: . .\build.ps1
pull_requests:
  do_not_increment_build_number: true
build: off
